# Generated by Django 3.2.9 on 2021-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('done', 'Done'), ('archived', 'Archived')], max_length=9)),
            ],
        ),
    ]
